### PR TITLE
Reverse proxy support

### PR DESCRIPTION
**Pull request by cha0s**
Parse the HTTP header and use it to determine the first untrusted address -- this is what we'll use to create the hash.

### CODE REVIEW

**Comment by samcday** [comment]
FYI this is something I tried doing a while ago with my [hotpotato](http://github.com/samcday/hotpotato) + [socketio-cluster](https://github.com/samcday/socketio-cluster) project.

Parsing payloads before sending connection descriptors is fraught with peril. When I load tested these approaches with anything more than a couple of hundred clients concurrently connecting, I observed Node actually dropping packets on the floor, resulting in the client receiving a HTTP request missing data (which is very bad, as you might imagine). I raised node#7905 for this particular problem, and it has since been fixed ... so *maybe* this approach works okay now. I haven't run extensive load + sanity tests on a recent version of Node though (last time I looked at this the latest version was 0.11.12).

**Comment by tonious** [comment]
FWIW, this PR is not compatible with node 0.12.0.  `parsers` is no longer an exported property of the `http` module.

**Comment by cha0s** [comment]
Interesting. I'll have to get caught up with the bleeding edge. Thanks 
for the tip!

**Comment by awolden** [comment]
@cha0s  I took your logic and made it compatible with newer versions of this library and node.

Here:
 #45

**Pull request closed without merging**
